version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Phoenix"
    open-pull-requests-limit: 2
    labels: ["dependencies"]
    groups:
      actions-minor-and-patch:
        update-types: ["minor", "patch"]
        
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Phoenix"
    open-pull-requests-limit: 0
    labels: ["dependencies"]
